[target.aarch64-apple-darwin]
rustflags = [
    "-C", "link-arg=-Wl,-headerpad_max_install_names",
    "-C", "link-arg=-Wl,-rpath,/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib"
]
